name: Update Nginx Port Forwarding

inputs:
  app_path:
    description: 'app path'
    required: true
    type: string
  new_port:
    description: 'new port for Nginx port forwarding'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Update Nginx port forwarding to ${{ inputs.new_port }}
      run: |
        ${{ inputs.app_path }}/change_nginx_port_forwarding.sh ${{ inputs.new_port }}
