name: rollback server

inputs:
  port:
    description: 'rollback port'
    required: true
    type: string
outputs:
  rollback_port:
    value: ${{ inputs.port }}

runs:
  using: 'composite'
  steps:
    - name: Execute rollback
      run: |
        echo "Deploy failed. Rollback server port: ${{ inputs.port }}"
        sudo lsof -t -i :${{ inputs.port }} | xargs kill -9
        exit 1
