version: "3.8"

services:
  ddangkong-api-dev:
    platform: linux/arm64/v8
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILE=dev
    ports:
      - "80:8080"
