spring:
  config:
    import: prod-secret.yml
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${secret.datasource.master.username}
      password: ${secret.datasource.master.password}
      url: jdbc:mysql://${secret.datasource.master.host}:${secret.datasource.master.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    slave1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${secret.datasource.slaves.slave1.username}
      password: ${secret.datasource.slaves.slave1.password}
      url: jdbc:mysql://${secret.datasource.slaves.slave1.host}:${secret.datasource.slaves.slave1.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000

server:
  port: ${secret.application.port}

cors:
  origin: ${secret.cors.origin}

logging:
  config: classpath:logback-prod.xml
  discord:
    webhook-url: ${secret.discord.webhook-url}
  location: ${secret.application.log.location}

management:
  endpoints:
    web:
      exposure:
        include: "health"
