spring:
  config:
    import: prod-secret.yml

  datasource:
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000

server:
  port: ${secret.application.port}

cors:
  origin: ${secret.cors.origin}

logging:
  config: classpath:logback-prod.xml
  discord:
    webhook-url: ${secret.discord.webhook-url}
  location: ${secret.application.log.location}
