#spring:
#
#  datasource:
#    url: jdbc:mysql://10.0.100.8:3306/ddangkong_10_000_000?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#    username: ddangkong
#    password: ddangkong
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show-sql: true
#        format-sql: true
#        highlight_sql: true
#        jdbc:
#          batch_size: 1000
#
#
#cors:
#  origin: "*"
#
#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: TRACE
#      springframework:
#        transaction:
#          interceptor: TRACE
