spring:
  config:
    import: dev-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secret.datasource.url}:${secret.datasource.port}/${secret.datasource.database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}
    hikari:
      minimum-idle: ${secret.datasource.hikari.minimum-idle}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

server:
  tomcat:
    threads:
      max: ${secret.server.tomcat.threads.max}

cors:
  origin: ${secret.cors.origin}

cookie:
  rejoin-key: ${secret.cookie.rejoin-key}

encrypt:
  secret-key: ${secret.encrypt.secret-key}
  algorithm: ${secret.encrypt.algorithm}

logging:
  config: classpath:logback-dev.xml
  location : ${secret.application.log.location}
  discord:
    webhook-url: ${secret.discord.webhook-url}
