spring:
  config:
    import: prod-secret.yml
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${secret.datasource.source.username}
      password: ${secret.datasource.source.password}
      jdbc-url: jdbc:mysql://${secret.datasource.source.host}:${secret.datasource.source.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    replica1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${secret.datasource.replica1.username}
      password: ${secret.datasource.replica1.password}
      jdbc-url: jdbc:mysql://${secret.datasource.replica1.host}:${secret.datasource.replica1.port}/${secret.datasource.database}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000

server:
  port: ${secret.application.port}

cors:
  origin: ${secret.cors.origin}

logging:
  config: classpath:logback-prod.xml
  discord:
    webhook-url: ${secret.discord.webhook-url}
  location: ${secret.application.log.location}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health"
