name: BE CD for Dev

on:
  workflow_dispatch:

  push:
    branches: [ "develop" ]
    paths:
      - backend/**

jobs:
  build:
    timeout-minutes: 2
    runs-on: [ self-hosted, linux, ARM64, dev ] # Self hosted runner 사용

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: bootJar with Gradle
        run: ./gradlew bootJar -PcreateRestDocs

      - name: Upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: build/libs/*.jar

  deploy:
    needs: build
    timeout-minutes: 2
    runs-on: [ self-hosted, linux, ARM64, dev ]

    steps:
      - name: Execute script on EC2 to deploy
        run: sudo sh ~/deploy-script-dev.sh

      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ~/app

      - name: Execute deploy script on EC2
        run: sudo sh ~/scripts/deploy-script-dev.sh
