name: BE CD for Dev

on:
  workflow_dispatch:

  push:
    branches: [ "develop" ]
    paths:
      - backend/**

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, ARM64] # Self hosted runner 사용
    steps:
      - name: Execute script on EC2 to deploy
        run: sudo sh ~/deploy-script-dev.sh
