name: BE CD for Dev

on:
  workflow_dispatch:

  push:
    branches: [ "develop" ]
    paths:
      - backend/**

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY_NAME: ddangkong/ddangkong-api-dev

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting application-dev.yml
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./src/main/resources/application-dev.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_GMAIL }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker compose -f deploy/docker-compose-dev.yml build 
          docker tag deploy-ddangkong-api-dev:latest $DOCKER_REPOSITORY_NAME:latest

      - name: Push Docker image
        run: docker push $DOCKER_REPOSITORY_NAME:latest

  deploy:
    needs: build
    timeout-minutes: 1
    runs-on: [ self-hosted, linux, ARM64 ] # Self hosted runner 사용
    env:
      DOCKER_REPOSITORY_NAME: ddangkong/ddangkong-api-dev
      CONTAINER_NAME: ddangkong-api-dev

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_GMAIL }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull docker image
        run: sudo docker pull $DOCKER_REPOSITORY_NAME:latest

      - name: Stop and Remove previous Docker container
        run: |
          CONTAINER_ID=$(sudo docker ps -aqf name=$CONTAINER_NAME)
          if [ -n ${CONTAINER_ID} ]; then
            sudo docker rm -f ${CONTAINER_ID}
          else
            echo "No previous container found with name. Skipping removal."
          fi

      - name: Remove previous Docker image
        run: |    
          IMAGE_ID=$(sudo docker images --filter=reference=ddangkong/ddangkong-api-dev --format "{{.ID}}")
          if [ -n ${IMAGE_ID} ]; then
            sudo docker rmi ${IMAGE_ID}
          else
            echo "No previous image found with repository name. Skipping removal."
          fi

      - name: Run new Docker container
        run: |
          sudo nohup docker run -p 80:8080 --name $CONTAINER_NAME \
          $DOCKER_REPOSITORY_NAME:latest > ~/dev-nohup.out 2>&1 &
