name: BE CD for Prod

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - backend/**

jobs:
  deploy:
    timeout-minutes: 3
    runs-on: [ self-hosted, linux, ARM64, prod ]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting prod-secret.yml
        run: |
          echo "${{ secrets.PROD_SECRET_YML }}" > ./src/main/resources/prod-secret.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Stop existing Java Application
        run: |
          if [ -f app.pid ]; then
          PID=$(cat app.pid)
          kill $PID
          rm -f app.pid
          echo "Existing Java application stopped with PID $PID"
          else
          echo "No existing application running."
          fi

      - name: Start Java Application
        run: |
          sudo nohup java -jar ddangkong-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod & 
          echo $! > app.pid
          echo "Java application started with PID $(cat app.pid)"
