name: Nginx Config Change

on:
  workflow_call:
    inputs:
      self_hosted_runner:
        description: '배포할 self-hosted 러너 이름'
        required: true
        type: string
      green_port:
        description: '그린 포트'
        required: true
        type: string

env:
  default_path: ~/app

jobs:
  change-nginx-config:
    runs-on: ${{ inputs.self_hosted_runner }}
    steps:
      - name: Change Nginx Config
        run: |
          ${{ env.default_path }}/change_nginx_config.sh ${{ inputs.green_port }}
          # actuator 포트 변경 보류
          # Nginx Config 변경
          # Nginx 재시작
          # Nginx Config 변경 확인
