name: FE CI for dev

on:
  pull_request:
    branches:
      - develop
    paths:
      - "frontend/**"

jobs:
  build-and-test:
    timeout-minutes: 4
    runs-on: [self-hosted, linux, ARM64]

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build
        run: npm run build-dev
        working-directory: ./frontend

      - name: Test
        run: npm test
        working-directory: ./frontend
