name: Update Nginx Port Forwarding

on:
  workflow_call:
    inputs:
      self_hosted_runner:
        description: 'self hosted runner label'
        required: true
        type: string
      app_path:
        description: 'app path'
        required: true
        type: string
      old_port:
        description: 'old port'
        required: true
        type: string
      new_port:
        description: 'new port for Nginx port forwarding'
        required: true
        type: string
      old_shutdown:
        description: 'shutdown before update'
        required: false
        type: boolean
      test:
        type: boolean
        required: false
    outputs:
      old_port:
        value: ${{ inputs.old_port }}
      new_port:
        value: ${{ inputs.new_port }}

jobs:
  old_shutdown:
    if: ${{ inputs.old_shutdown }}
    uses: ./.github/workflows/shutdown.yml
    with:
      self_hosted_runner: ${{ inputs.self_hosted_runner }}
      port: ${{ inputs.old_port }}

  update-nginx-port-forwarding:
    runs-on: ${{ inputs.self_hosted_runner }}
    steps:
      - name: rollback test ${{ runner.name }}, ${{ inputs.test }}
        if: ${{ runner.name == 'ip-10-0-21-212' && inputs.test }}
        run: exit 1

      - name: Update Nginx port forwarding from ${{ inputs.old_port }} to ${{ inputs.new_port }}
        run: ${{ inputs.app_path }}/change_nginx_port_forwarding.sh ${{ inputs.old_port }} ${{ inputs.new_port }}
      
      - name: Reload Nginx
        run: sudo nginx -s reload # todo 에러 처리
