name: Self-hosted Runner Deployment

on:
  workflow_call:
    inputs:
      self_hosted_runner:
        description: '배포할 self-hosted 러너 이름'
        required: true
        type: string
      artifact_name:
        description: 'artifact 이름'
        required: true
        type: string
      jar_name:
        description: '배포할 jar 파일 이름'
        required: true
        type: string
      profile:
        description: '배포할 프로파일'
        required: true
        type: string
    outputs:
      green_port: 
        description: '그린 포트'
        value: ${{ jobs.deploy.outputs.port }}
        
env:
  default_path: ~/app

jobs:
  deploy:
    runs-on: ${{ inputs.self_hosted_runner }}
    outputs:
      port: ${{ steps.green-port.outputs.port }}
    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.artifact_name }}
            path: ${{ env.default_path }}

      - name: Get Green Port
        id: green-port
        run: |
          ${{ env.default_path }}/get_green_port.sh | awk '{print "port=$0"}' >> $GITHUB_OUTPUT

      - name: Start Java Application
        run: sudo nohup java --Dspring.profiles.active=${{ inputs.profile }} --Dserver.port=${{ steps.green-port.outputs.port }} --Duser.timezone=Asia/Seoul -jar ${{ env.default_path }}/${{ inputs.jar_name }} &
  
  health-check:
    needs: deploy
    runs-on: ${{ inputs.self_hosted_runner }}
    steps:
      - name: Health Check
        run: |
          ${{ env.default_path }}/green_health_check.sh ${{ needs.deploy.outputs.port }}

  debug:
    needs: health-check
    runs-on: ubuntu-latest
    if: ${{ needs.health-check.result == failure() }}
    steps:
      - name: Debug
        run: echo "Deploy failed" # 추후 수정
