name: Self-hosted Runner Deployment

on:
  workflow_call:
    inputs:
      self_hosted_runner:
        description: 'self hosted runner label'
        required: true
        type: string
      artifact_name:
        description: 'artifact name'
        required: true
        type: string
      jar_name:
        description: 'jar name'
        required: true
        type: string
      profile:
        description: 'profile'
        required: true
        type: string
      app_path:
        description: 'app path'
        required: true
        type: string
    outputs:
      green_port:
        value: ${{ jobs.deploy.outputs.green_port }}
      blue_port:
        value: ${{ jobs.deploy.outputs.blue_port }}

jobs:
  deploy:
    runs-on: ${{ inputs.self_hosted_runner }}
    outputs:
      green_port: ${{ steps.blue_green_port.outputs.green_port }}
      blue_port: ${{ steps.blue_green_port.outputs.blue_port }}
    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.artifact_name }}
            path: ${{ inputs.app_path }}

      - name: Get Blue Green Port
        id: blue_green_port
        run: |
          chmod +x ${{ inputs.app_path }}/*.sh && \
          ${{ inputs.app_path }}/get_blue_green_port.sh >> $GITHUB_OUTPUT

      - name: Start Java Application
        run: sudo nohup java -Dspring.profiles.active=${{ inputs.profile }} -Dserver.port=${{ steps.blue_green_port.outputs.green_port }} -Duser.timezone=Asia/Seoul -jar ${{ inputs.app_path }}/${{ inputs.jar_name }} &

      - name: Health Check
        run: |
          ${{ inputs.app_path }}/green_health_check.sh ${{ steps.blue_green_port.outputs.green_port }}

      - name: test
        if: runner.name == 'ip-10-0-21-212'
        run: |
          exit 1
