name: Self-hosted Runner Deployment

on:
  workflow_call:
    inputs:
      self_hosted_runner:
        description: '배포할 self-hosted 러너 이름'
        required: true
        type: string
      artifact_name:
        description: 'artifact 이름'
        required: true
        type: string
      jar_name:
        description: '배포할 jar 파일 이름'
        required: true
        type: string
      profile:
        description: '배포할 프로파일'
        required: true
        type: string
        
env:
  default_path: ~/app

jobs:
  deploy:
    runs-on: ${{ inputs.self_hosted_runner }}
    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.artifact_name }}
            path: ${{ env.default_path }}

      - name: Get Blue Green Port
        id: blue_green_port
        run: |
          chmod +x ${{ env.default_path }}/*.sh && \
          ${{ env.default_path }}/get_blue_green_port.sh | awk '{print $0}' >> $GITHUB_OUTPUT
      
      - name: test
        run: | 
          echo ${{ steps.blue_green_port.outputs.green_port }}
          echo ${{ steps.blue_green_port.outputs.blue_port }}

      - name: Start Java Application
        run: sudo nohup java -Dspring.profiles.active=${{ inputs.profile }} -Dserver.port=${{ steps.blue_green_port.outputs.green_port }} -Duser.timezone=Asia/Seoul -jar ${{ env.default_path }}/${{ inputs.jar_name }} &
      
      - name: Health Check
        run: |
          ${{ env.default_path }}/green_health_check.sh ${{ steps.blue_green_port.outputs.green_port }}

      - name: fail
        if: ${{ failure() }} # 추후 수정
        run: | 
          echo "Deploy failed"
          sudo lsof -i :${{ steps.blue_green_port.outputs.green_port }} | awk 'NR!=1 {print $2}' | xargs kill -9
          exit 1
